import 'jquery'
import 'jquery_ujs'
import 'popper'
import 'bootstrap'
import '@hotwired/turbo-rails'
import 'controllers'
import 'trix'
import '@rails/actiontext'
import "chartkick"
import "Chart.bundle"