name: Deploy EasyRemplacement

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.151.0
        with:
          ruby-version: '3.2.2'

      - name: Install Rails
        run: gem install rails -v 7.0.5

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails db:seed

      - name: Deploy to Server
        run: |
          